# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-05 21:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('play_pi', '0006_playlist_tracks'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='radiostation',
            options={'ordering': ('order',)},
        ),
        migrations.AddField(
            model_name='radiostation',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
