# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-08 19:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('play_pi', '0008_auto_20160808_1329'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='rating',
            field=models.SmallIntegerField(choices=[(0, 'No rating'), (1, 'Thumbs down'), (5, 'Thumbs up')], default=0),
        ),
    ]
