# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-18 20:29
from __future__ import unicode_literals

from django.db import migrations, models
import sortedm2m.fields
from sortedm2m.operations import AlterSortedManyToManyField


class Migration(migrations.Migration):

    dependencies = [
        ('play_pi', '0009_track_rating'),
    ]

    operations = [
        AlterSortedManyToManyField (
            model_name='playlist',
            name='tracks',
            field=sortedm2m.fields.SortedManyToManyField(help_text=None, related_name='playlists', through='play_pi.PlaylistConnection', to='play_pi.Track'),
        ),
        migrations.AddField(
            model_name='playlistconnection',
            name='sort_value',
            field=models.IntegerField(default=0),
        ),
    ]
