# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-31 17:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('play_pi', '0010_auto_20161018_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='art_url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='artist',
            name='art_url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
