# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-04 21:19
from __future__ import unicode_literals

from django.db import migrations

DEFAULT_BCM_PLAY = 18
DEFAULT_BCM_NEXT = 17
DEFAULT_BCM_PREVIOUS = 22
DEFAULT_BCM_STOP = 27
DEFAULT_BCM_VOLUME_UP = 20
DEFAULT_BCM_VOLUME_DOWN = 21

default_buttons = [
    (DEFAULT_BCM_PLAY, b'play'),
    (DEFAULT_BCM_NEXT, b'next'),
    (DEFAULT_BCM_PREVIOUS, b'previous'),
    (DEFAULT_BCM_STOP, b'stop'),
    (DEFAULT_BCM_VOLUME_UP, b'volume_up'),
    (DEFAULT_BCM_VOLUME_DOWN, b'volume_down'),
]


def create_default_buttons(apps, schema_editor):
    GpioButton = apps.get_model('hardware', 'GpioButton')
    GpioButton.objects.bulk_create([GpioButton(bcm_pin=pin, action=action, enable=False) for pin, action in default_buttons])


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_default_buttons),
    ]
